knp_snappy:
    pdf:
        enabled:    true
        binary:     '/usr/bin/wkhtmltopdf'
        options:
            - { name: 'viewport-size', value: '1024x768' }
            - { name: 'page-size', value: 'A4' }
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
