<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1UhKBMC\srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1UhKBMC/srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1UhKBMC.legacy');

    return;
}

if (!\class_exists(srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1UhKBMC\srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer::class, srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer::class, false);
}

return new \Container1UhKBMC\srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer([
    'container.build_hash' => '1UhKBMC',
    'container.build_id' => '4313c282',
    'container.build_time' => 1717154243,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1UhKBMC');
