<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerACD6JC4\srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerACD6JC4/srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerACD6JC4.legacy');

    return;
}

if (!\class_exists(srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerACD6JC4\srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer::class, srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer::class, false);
}

return new \ContainerACD6JC4\srcMyCoon_Apps_Backoffice_Backend_KernelDevDebugContainer([
    'container.build_hash' => 'ACD6JC4',
    'container.build_id' => '7ab477fe',
    'container.build_time' => 1666873763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerACD6JC4');
