<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHkxDorE\srcMyCoon_Apps_Backoffice_Backend_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHkxDorE/srcMyCoon_Apps_Backoffice_Backend_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHkxDorE.legacy');

    return;
}

if (!\class_exists(srcMyCoon_Apps_Backoffice_Backend_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerHkxDorE\srcMyCoon_Apps_Backoffice_Backend_KernelTestDebugContainer::class, srcMyCoon_Apps_Backoffice_Backend_KernelTestDebugContainer::class, false);
}

return new \ContainerHkxDorE\srcMyCoon_Apps_Backoffice_Backend_KernelTestDebugContainer([
    'container.build_hash' => 'HkxDorE',
    'container.build_id' => '199f4be5',
    'container.build_time' => 1717155198,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHkxDorE');
